// sdks/frontend/embedded/library/packages/react/src/connect-dialog/components/connect-button.tsx
"use client";
import * as React from "react";

interface CloseButtonProps {
  onClose?: (e: any) => void;
}

function ConnectButton(props: CloseButtonProps) {
  return (
    <>
      <button
        className="button-26b64d18"
        onClick={(e) => props.onClose && props.onClose(e)}
      >
        Connect
      </button>

      <style>{`.button-26b64d18 {
  background-color: #000;
  border-radius: 10px;
  cursor: pointer;
  font-size: 1rem;
  padding: 0.7rem;
  right: 0.4rem;
  top: 0.4rem;
  outline: none;
  border: none;
  font-weight: 500;
  color: #fff;
  width: 100%;
}`}</style>
    </>
  );
}

export default ConnectButton;

// sdks/frontend/embedded/library/packages/svelte/src/connect-dialog/components/connect-button.svelte
<script context="module" lang="ts">
  interface CloseButtonProps {
    onClose?: (e: any) => void;
  }
</script>

<script lang="ts">
  export let onClose: CloseButtonProps["onClose"] = undefined;
</script>

<button
  class="button"
  on:click={(e) => {
    onClose && onClose(e);
  }}
>
  Connect
</button>

<style>
  .button {
    background-color: #000;
    border-radius: 10px;
    cursor: pointer;
    font-size: 1rem;
    padding: 0.7rem;
    right: 0.4rem;
    top: 0.4rem;
    outline: none;
    border: none;
    font-weight: 500;
    color: #fff;
    width: 100%;
  }
</style>
