// sdks/frontend/embedded/library/packages/svelte/src/connect-dialog/components/workflows/workflows-list.svelte
<script context="module" lang="ts">
  interface WorkflowsListProps {
    workflows?: Workflow[];
  }
</script>

<script lang="ts">
  import { Workflow } from "../../../middleware/model/Workflow";
  import WorkflowsItem from "./workflows-item.svelte";

  export let workflows: WorkflowsListProps["workflows"] = undefined;
</script>

<div class="div">
  {#each workflows as workflow (workflow.workflowReferenceCode)}
    <WorkflowsItem {workflow} />
  {/each}
</div>

<style>
  .div {
    overflow-y: auto;
    max-height: 600px;
  }
</style>

// sdks/frontend/embedded/library/packages/react/src/connect-dialog/components/workflows/workflows-list.tsx
import * as React from "react";

interface WorkflowsListProps {
  workflows?: Workflow[];
}

import { Workflow } from "../../../middleware/model/Workflow";
import WorkflowsItem from "./workflows-item";

function WorkflowsList(props: WorkflowsListProps) {
  return (
    <>
      <div className="div-f9f2c908">
        {props.workflows?.map((workflow) => (
          <WorkflowsItem
            key={workflow.workflowReferenceCode}
            workflow={workflow}
          />
        ))}
      </div>

      <style>{`.div-f9f2c908 {
  overflow-y: auto;
  max-height: 600px;
}`}</style>
    </>
  );
}

export default WorkflowsList;
