// sdks/frontend/embedded/library/packages/react/src/connect-dialog/components/tabs/tabs-list-button.tsx
"use client";
import * as React from "react";

export interface TabsListButtonProps {
  activeTab: string;
  id: string;
  label: string;
  onClick: (tabId: string) => void;
}

function TabsListButton(props: TabsListButtonProps) {
  return (
    <>
      <button
        role="tab"
        className="button-07b505a2"
        key={`tab-btn-${props.id}`}
        id={`tab-${props.id}`}
        aria-controls={`panel-${props.id}`}
        aria-selected={props.activeTab === props.id}
        onClick={(event) => props.onClick(props.id)}
        style={{
          color: props.activeTab === props.id ? "#2563EB" : "inherit",
          borderColor: props.activeTab === props.id ? "#2563EB" : "transparent",
        }}
      >
        {props.label}
      </button>

      <style>{`.button-07b505a2 {
  font-size: 0.9rem;
  padding: 0.75em 1em;
  background-color: transparent;
  border: 2px solid #ddd;
  border-width: 0 0 2px;
  cursor: pointer;
  white-space: nowrap;
}`}</style>
    </>
  );
}

export default TabsListButton;

// sdks/frontend/embedded/library/packages/svelte/src/connect-dialog/components/tabs/tabs-list-button.svelte
<script context="module" lang="ts">
  export interface TabsListButtonProps {
    activeTab: string;
    id: string;
    label: string;
    onClick: (tabId: string) => void;
  }
</script>

<script lang="ts">
  export let id: TabsListButtonProps["id"];
  export let activeTab: TabsListButtonProps["activeTab"];
  export let onClick: TabsListButtonProps["onClick"];
  export let label: TabsListButtonProps["label"];
  function stringifyStyles(stylesObj) {
    let styles = "";
    for (let key in stylesObj) {
      const dashedKey = key.replace(/[A-Z]/g, function (match) {
        return "-" + match.toLowerCase();
      });
      styles += dashedKey + ":" + stylesObj[key] + ";";
    }
    return styles;
  }
</script>

<button
  style={stringifyStyles({
    color: activeTab === id ? "#2563EB" : "inherit",
    borderColor: activeTab === id ? "#2563EB" : "transparent",
  })}
  role="tab"
  class="button"
  key={`tab-btn-${id}`}
  id={`tab-${id}`}
  aria-controls={`panel-${id}`}
  aria-selected={activeTab === id}
  on:click={(event) => {
    onClick(id);
  }}>{label}</button
>

<style>
  .button {
    font-size: 0.9rem;
    padding: 0.75em 1em;
    background-color: transparent;
    border: 2px solid #ddd;
    border-width: 0 0 2px;
    cursor: pointer;
    white-space: nowrap;
  }
</style>
