// sdks/frontend/embedded/library/packages/react/src/connect-dialog/components/workflows/workflows-list.tsx
import * as React from "react";

interface WorkflowsListProps {
  workflows?: Workflow[];
}

import { Workflow } from "../../../middleware/model/Workflow";
import WorkflowsItem from "./workflows-item";

function WorkflowsList(props: WorkflowsListProps) {
  return (
    <>
      <div className="div-f9f2c908">
        {props.workflows?.map((workflow) => (
          <WorkflowsItem
            key={workflow.workflowReferenceCode}
            workflow={workflow}
          />
        ))}
      </div>

      <style>{`.div-f9f2c908 {
  overflow-y: auto;
  max-height: 600px;
}`}</style>
    </>
  );
}

export default WorkflowsList;

// sdks/frontend/embedded/library/packages/vue/src/connect-dialog/components/workflows/workflows-list.vue
<template>
  <div class="div">
    <template
      :key="workflow.workflowReferenceCode"
      v-for="(workflow, index) in workflows"
    >
      <WorkflowsItem :workflow="workflow"></WorkflowsItem>
    </template>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

import { Workflow } from "../../../middleware/model/Workflow";
import WorkflowsItem from "./workflows-item.vue";

interface WorkflowsListProps {
  workflows?: Workflow[];
}

export default defineComponent({
  name: "workflows-list",
  components: { WorkflowsItem: WorkflowsItem },
  props: ["workflows"],
});
</script>

<style scoped>
.div {
  overflow-y: auto;
  max-height: 600px;
}
</style>
